from setuptools import setup, find_packages

setup(
    name="deal-hunter",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "Django>=4.2.0",
        "django-celery-beat>=2.5.0",
        "django-crispy-forms>=2.0",
        "crispy-bootstrap5>=0.7",
        "celery>=5.3.0",
        "redis>=5.0.0",
        "firebase-admin>=6.0.0",
        "selenium>=4.10.0",
        "beautifulsoup4>=4.10.0",
        "requests>=2.28.0",
        "python-decouple>=3.7",
        "Pillow>=10.0.0",
    ],
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="A Django admin dashboard for managing bank deals web scraping",
    keywords="web, scraping, django, dashboard, admin, deals, banks",
    url="https://github.com/yourusername/deal-hunter",
    project_urls={
        "Bug Tracker": "https://github.com/yourusername/deal-hunter/issues",
        "Documentation": "https://github.com/yourusername/deal-hunter",
        "Source Code": "https://github.com/yourusername/deal-hunter",
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Framework :: Django",
        "Framework :: Django :: 4.2",
    ],
)