# Generated by Django 4.2.8 on 2025-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='process_id',
            field=models.IntegerField(blank=True, help_text='The PID of the process running this job', null=True),
        ),
    ]
