# Generated by Django 4.2.8 on 2025-05-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_scrapingjob_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
    ]
